name: ChatGPT Query

on:
  push:
    branches:
      - main

jobs:
  chatgpt_query:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Read code from file
      id: read-code
      run: |
        code=$(cat player.py)
        echo "::set-output name=code::$code"

    - name: Query ChatGPT
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        escaped_code= echo "yo"
        response=$(curl https://api.openai.com/v1/chat/completions -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $OPENAI_API_KEY" -d "{\"model\": \"gpt-3.5-turbo\", \"prompt\": \"Given the following code:\\n\\n\`\`\`python\\n$escaped_code\\n\`\`\`\\n\\nWhat does this code do? Explain its functionality.\", \"temperature\": 0.7}")

        echo "$response"

#escaped_code=$(echo "$CODE" | head -n 5)

